name: Run Maestro Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          build-tools: 33.0.0

      - name: Start Android Emulator
        run: |
          echo "no" | avdmanager create avd -n test_avd -k "system-images;android-33;google_apis;x86_64" --force
          emulator -avd test_avd -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Install Maestro CLI
        run: |
          curl -sSfL https://install.maestro.mobile.dev | bash
          export PATH="$HOME/.maestro/bin:$PATH"
          maestro doctor

          
   - name: Download APK
     run: https://namespace-team.slack.com/files/U0ADPN05KPX/F08GU554KNJ/mda-2.2.0-25.apk

    - name: Install APK
      run: adb install mda-2.2.0-25.apk


      - name: Run Maestro Tests
        run: |
          export PATH="$HOME/.maestro/bin:$PATH"
          maestro test draw.yaml
          maestro test login.yaml
          maestro test sort.yaml
          maestro test addtocart.yaml
          maestro test sauce-demo.yaml
